### ISSUE TITLE
MPO to dense numpy MPO with matching bond dims? 

### ISSUE THREAD

**Issue by h-larsson** [block-hczhai/pyblock3-preview#14]
I'd like to get the dense MPO tensors. 
```
from pyblock3.hamiltonian import Hamiltonian
from pyblock3.fcidump import FCIDUMP

fd = 'data/H8.STO6G.R1.8.FCIDUMP'
hamil = Hamiltonian(FCIDUMP(pg='d2h').read(fd), flat=True)
mpo = hamil.build_qc_mpo()
for n, tensor in enumerate(mpo.tensors):
    print(f"Tensor at site {n}: shape = {tensor.to_dense().shape}")
```
Should give me them but the shapes/bond dims are not matching:
```
Tensor at site 0: shape = (1, 4, 4, 26)
Tensor at site 1: shape = (46, 4, 4, 82)
```
26 is not 46, so I do not know how to contract the tensors. 

`mpo.compress` can help with this but this not always works.
Is it possible to get matching dense tensors? 
I see that some of the entries of the tensors are completely zero, which may be the reason why the bond dimensions do not match.

**Comment by hczhai** [comment]
You can add a line ``mpo = mpo.to_non_flat().to_sliceable()`` after ``mpo = hamil.build_qc_mpo()`` to solve the problem.

``SparseTensor.to_dense`` has an optional argument ``infos``. When you want to match virtual bond dimensions, you can compute "common infos" for each pair of adjacent tensors, and use these ``infos`` in ``SparseTensor.to_dense`` so that the missing blocks will be considered. This procedure is already implemented in ``MPS.to_sliceable()`` (https://github.com/block-hczhai/pyblock3-preview/blob/p0.2.9rc5/pyblock3/algebra/mps.py#L632-L649) so if you first call this method then the virtual bond dimensions will always match.

Please also note that the simple contraction of "dense" version of fermionic tensors in general will not lead to any meaningful results. To handle fermion signs, one needs at least Z2 symmetry blocks. But in a dense version of tensors the Z2 symmetry labels are erased.

Alternatively, one can first do Jordan-Wigner transformation of the Hamiltonian and then construct the MPO, which can then be contacted using normal tensor contraction rules. If you are interested in this representation of dense MPO (which is available in block2) please let me know.

**Comment by h-larsson** [comment]
Thanks very much, Huanchen! Yes, I wanted to get the JW-transformed Hamiltonian.

**Comment by hczhai** [comment]
Hi Henrik,

Please see if the following can be helpful.

1. It depends purely on in ``block2==0.5.3`` (no need to ``import pyblock3``).
2. It constructs MPO and runs DMRG with all symmetry disabled, so ``to_dense`` is not needed. Each MPO and MPS tensor will only have one block.
3. The Jordan-Wigner transformation is implicitly done inside ``driver.get_qc_mpo`` before constructing MPO.
4. The ``bond_dim_setter`` part and ``cutoff=-0.1`` can be deleted if you do not need a fine control of MPS bond dimension.

```python3
import numpy as np
from pyblock2._pyscf.ao2mo import integrals as itg
from pyblock2.driver.core import DMRGDriver, SymmetryTypes
from pyblock2.algebra.io import MPSTools, MPOTools
from pyscf import gto, scf

bond_dims = [50] * 4 + [100] * 6
noises = [1e-4] * 4 + [1e-5] * 4 + [0]
thrds = [1e-10] * 10

mol = gto.M(atom="H 0 0 0; H 0 0 1; H 0 1 0; H 0 1 1", basis="sto3g", verbose=0)
mf = scf.GHF(mol).run(conv_tol=1E-14)
ncas, n_elec, spin, ecore, h1e, g2e, orb_sym = itg.get_ghf_integrals(mf, ncore=0, ncas=None, g2e_symm=8)

# disable all symmetry groups. use qubit basis and spin operators
driver = DMRGDriver(scratch="./tmp", symm_type=SymmetryTypes.SAny | SymmetryTypes.SGB, n_threads=4)
driver.set_symmetry_groups()
site_basis = [[(driver.bw.SX(), 2)]] * ncas
ops = {"": np.array([[1, 0], [0, 1]]), "P": np.array([[0, 1], [0, 0]]),
    "M": np.array([[0, 0], [1, 0]]), "Z": np.array([[0.5, 0], [0, -0.5]])}
site_ops = [ops] * ncas

driver.initialize_system(n_sites=ncas, vacuum=driver.bw.SX(), target=driver.bw.SX(), hamil_init=False)
driver.ghamil = driver.get_custom_hamiltonian(site_basis, site_ops)

mpo = driver.get_qc_mpo(h1e=h1e, g2e=g2e, ecore=ecore, add_ident=False, simple_const=True, iprint=1)

# constrain the MPS bond dimension to get a very standard MPS
@driver.set_callback
def bond_dim_setter(event, iprint):
    if event == "DMRG::sweep.start":
        driver._dmrg.site_dependent_bond_dims = driver.bw.b.VectorVectorUInt32([driver.bw.b.VectorUInt32(
            [min(a, b, bond_dims[driver._dmrg.isweep]) for x in [[2 ** (i + 1) for i in range(ncas - 1)]] for a, b in zip(x, x[::-1])])])

mpo = driver.get_qc_mpo(h1e=h1e, g2e=g2e, ecore=ecore, add_ident=False, simple_const=True, iprint=1)
ket = driver.get_random_mps(tag="KET", bond_dim=50, nroots=1)

# make sure an even number of sweep is performed by setting "tol=0"
energy = driver.dmrg(mpo, ket, n_sweeps=len(bond_dims), bond_dims=bond_dims, noises=noises,
    thrds=thrds, cutoff=-0.1, tol=0.0, iprint=1)
print('DMRG  energy = %20.15f' % energy)

assert ket.center == 0
ket = driver.adjust_mps(ket, dot=1)[0]
pympo = MPOTools.from_block2(mpo.prim_mpo)
pyket = MPSTools.from_block2(ket)
print('pyket energy = %20.15f' % (pyket.conj() @ (pympo @ pyket)))

# contract MPO and MPS to matrix and vector
mat = np.array(pympo.tensors[0].blocks[0].reduced)
vec = np.array(pyket.tensors[0].blocks[0].reduced)
for i in range(1, driver.n_sites):
    mat = np.tensordot(mat, pympo.tensors[i].blocks[0].reduced, axes=(-1, 0))
    vec = np.tensordot(vec, pyket.tensors[i].blocks[0].reduced, axes=(-1, 0))
mat = mat.transpose((*range(0, len(mat.shape), 2), *range(1, len(mat.shape), 2)))
vec = vec.reshape((-1, 1))
mat = mat.reshape((vec.shape[0], vec.shape[0]))
print('dense energy = %20.15f' % (vec.conj().T @ mat @ vec)[0, 0])
```

**Comment by h-larsson** [comment]
Thanks a lot, Huanchen! That works nicely.
